export const actionTypes = {
  MERGE_CUBES_INTRO: 'MERGE_CUBES_INTRO',
  MERGE_CUBES_CONCLUSION: 'MERGE_CUBES_CONCLUSION',
  SAVE_THUMB: 'SAVE_THUMB',
  REGISTER_GL: 'REGISTER_GL',
  STORE_GLTF: 'STORE_GLTF',
  SAVE_GLTF: 'SAVE_GLTF',
  MERGE_COMPLETE: 'MERGE_COMPLETE',
};
